---
- name: Power OpenStack Instance
  hosts: localhost
  connection: local
  tasks:

    - name: Setar mensagem para registro no SDM - andamento
      # Mensagem para inserir no ticket de acordo com o fluxo do workflow
      ansible.builtin.set_stats:
        data:
          comment_log: >
            Operação de: {{ vm_action }} na vm: {{ vm_name }} realizada com sucesso,
            job id: {{ tower_workflow_job_id | default(tower_job_id) }},
            operador: {{ tower_user_name }}
            {% if tower_user_first_name or tower_user_last_name -%}
              ({{ tower_user_first_name | default('') }} {{ tower_user_last_name | default('') }})
            {%- endif %},
            comentário do operador: {{ ansible_log | default('') }}

  roles:
    - name: ../roles/power_vm
